name: twitter_oembed_api
description: This library provides the easiest way to use the Twitter oEmbed API in Dart and Flutter apps.
version: 0.1.0
repository: https://github.com/twitter-dart/twitter-oembed-api
issue_tracker: https://github.com/twitter-dart/twitter-oembed-api/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.6
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  freezed: ^2.3.3
  import_sorter: ^4.6.0